### ISSUE TITLE
'main' panicked at 'attempt to divide by zero', raqote-0.7.3/src/rasterizer.rs:135:25

### ISSUE THREAD

**Issue by ivanceras** [jrmuizel/raqote#88]
I managed to trigger a divide by zero using the svg at the bottom.

The raqote backend was used in [resvg crate](https://github.com/RazrFalcon/resvg) example.

Here is the backtrace.

```sh
RUST_BACKTRACE=1 cargo run --release --features "raqote-backend" --example minimal -- simple.svg simple.png
    Finished release [optimized] target(s) in 0.03s
     Running `target/release/examples/minimal simple.svg simple.png`
thread 'main' panicked at 'attempt to divide by zero', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/raqote-0.7.3/src/rasterizer.rs:135:25
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:76
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:60
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:64
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:196
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:473
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:380
  12: rust_begin_unwind
             at src/libstd/panicking.rs:307
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
  14: core::panicking::panic
             at src/libcore/panicking.rs:49
  15: raqote::rasterizer::ActiveEdge::step
  16: raqote::rasterizer::Rasterizer::rasterize
  17: raqote::draw_target::DrawTarget::fill
  18: raqote::draw_target::DrawTarget::stroke
  19: resvg::backend_raqote::style::stroke
  20: resvg::backend_raqote::path::draw
  21: resvg::backend_raqote::render_node
  22: resvg::backend_raqote::render_group
  23: resvg::backend_raqote::render_node
  24: resvg::backend_raqote::render_node_to_canvas_impl
  25: resvg::backend_raqote::render_to_canvas
  26: resvg::backend_raqote::render_to_image
  27: <resvg::backend_raqote::Backend as resvg::Render>::render_to_image
  28: minimal::main
  29: std::rt::lang_start::{{closure}}
  30: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  31: std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  32: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  33: std::panicking::try
             at src/libstd/panicking.rs:271
  34: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  35: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  36: main
  37: __libc_start_main
  38: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

This is the [simple.svg](https://gist.github.com/ivanceras/20cd58f64ca5ae7e963e428fa0eb6c24) used

Edited: Linked the archived svg file

**Comment by RazrFalcon** [comment]
Could you replace embedded SVG with an archive?

**Comment by RazrFalcon** [comment]
Can confirm. It crashes during stroking:

```
Path { ops: [MoveTo((0.0,0.0)), LineTo((940.0,0.0)), LineTo((940.0,11740.0)), LineTo((0.0,11740.0)), Close], winding: NonZero }
```

**Comment by jrmuizel** [comment]
It looks like this is caused by the large coordinates. I'll look into a fix.
